name: "Create Git Tag for Branch"
description: "Create a git tag on a specific branch using GitHub API and pwsh"
author: Lee Lott

inputs:
  branch-name:
    description: 'Branch name on which to create the tag (e.g., main)'
    required: true
  tag-name:
    description: 'Name of the tag to create'
    required: true
  tag-message:
    description: 'Tag message (optional)'
    required: false
    default: ''
  commit-sha:
    description: 'Optionally specify a commit SHA to tag instead of the head of the branch.'
    required: false
    default: ''    
  org-name:
    description: 'The name of the GitHub organization'
    required: true
  repo-name:
    description: 'The name of the repository'
    required: true
  token:
    description:  'GitHub token with access to Git tags'
    required: true

outputs:
  result:
    description: 'Result of the attempt to merge the Pull Request ("success" or "failure")'
    value: ${{ steps.action.outputs.result }}
  error-message:
    description: 'Error message if the Pull Request merge fails'
    value: ${{ steps.action.outputs.error-message }}
    
runs:
  using: "composite"
  steps:
    - name: Create Tag for Branch
      id: action
      shell: pwsh
      run: |
        Import-Module "${{ github.action_path }}/modules/Add-GitTag.psm1"
        Add-GitTag `
          -RepoName "${{ inputs.repo-name }}" `
          -OrgName "${{ inputs.org-name }}" `
          -BranchName "${{ inputs.branch-name }}" `
          -TagName "${{ inputs.tag-name }}" `
          -TagMessage "${{ inputs.tag-message }}" `
          -CommitSha "${{ inputs.commit-sha }}" `
          -Token "${{ inputs.token }}"